# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push
name: add-path
# comment
jobs:
  test:
    runs-on: windows-latest
    steps:

      - name: Create folder
        run: mkdir C:\actions-bin
        shell: cmd

      - name: Create batch script
        run: echo @echo Called from PATH > C:\actions-bin\test-path.bat
        shell: cmd

      - name: Update path
        run: echo "::add-path::C:\actions-bin"

      - name: Run
        run: test-path
        shell: cmd

      - name: Show path from Powershell
        run: echo $($env:path -split ";")

      - name: Show path from Bash
        run: echo $PATH | tr ":" "\n"
        shell: bash

      - name: Show path from Cmd
        run: echo %PATH:;= & echo.%
        shell: cmd

      - name: Show path from bin/bash
        run: "C:\Program Files\Git\bin\bash.exe" -c 'echo $PATH | tr ":" "\n"'
        shell: cmd

      - name: Show path from usr/bin/bash
        run: "C:\Program Files\Git\usr\bin\bash.exe" -c 'echo $PATH | tr ":" "\n"'
        shell: cmd
