# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push
name: paths
# comment
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Show native paths
        run: .\paths.ps1
        shell: powershell

      - name: Show Git Bash paths
        run: powershell -File paths.ps1
        shell: bash
