# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push
name: paths
# comment
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Show native paths
        run: .\paths.ps1
        shell: pwsh

      - name: Show Git Bash paths
        run: pwsh -File paths.ps1
        shell: bash

      - name: Show Git Bash paths from bin
        run: "%PROGRAMFILES%\Git\bin\bash.exe" -c 'pwsh -File paths.ps1'
        shell: cmd

      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: logs
          path: logs
