# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push
name: paths
# comment
jobs:
  test:
    runs-on: windows-latest
    steps:

      - name: Show native paths
        run: ./paths.ps1
        shell: pwsh

      - name: Show Git Bash paths
        run: pwsh -File paths.ps1
        shell: bash
